name: cosmicview
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:

  auto_route: ^5.0.4
  badges: ^3.0.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flash: ^2.0.5+1
  floor: ^1.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_config: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^2.0.1
  flutter_markdown: ^0.6.13
  flutter_screenutil: ^5.7.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http_mock_adapter: ^0.3.3
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  loggy: ^2.0.3
  mockito: ^5.3.2
  mocktail: ^0.3.0
  package_info_plus: ^3.0.3
  percent_indicator: ^4.2.2
  pinput: ^2.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  reactive_forms: ^14.1.0
  rive: ^0.10.3
  shared_preferences: ^2.0.15
  sqflite: ^2.2.3
  styled_text: ^7.0.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  floor_generator: ^1.4.1
  flutter_gen_runner: ^5.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true


  assets:
    - .env
    - assets/images/
    - assets/animation/

